### ISSUE TITLE
Request to update README 

### ISSUE THREAD

**Issue by urmomseksy** [lochidev/TextComparePro#3]
I've never used Espanso but I'm going through the help documents and no matter what I try I can't seem to successfully add an option to insert the current date correctly using a trigger. Any chance you can update the readme to give at least one example of something like that?

Also, when I fill out the required information for advanced options for Espanso users, it does not seem to save or even have an option to save or add the trigger.

Thanks, I really love this app and I appreciate all of your hard work.

**Comment by lochidev** [comment]
I've updated the readme with an example config file! You can download it directly to your phone and import it. Regarding the UI, it only allows you to add 1 variable (unlimited in the configs). You can add it using the add button for the trigger. I'll work on the UI soon so it becomes more obvious, but for now, I think you'll be able to figure it out by looking at the feature graphics on the playstore and izzyondroid. Sorry for being late to add this small update, I've had a few health problems 😂 ♥ (there's also a bug related to dates where you can't have a negative offeset, I'll fix it in the next update)!
