### ISSUE TITLE
[Request Feature] a cursor

### ISSUE THREAD

**Issue by OilSubjectLoss7** [lochidev/TextComparePro#5]
similar in Text Expand.   
you can like put a cursor position anywhere you want   

foo[cursor]bar  
foobar[cursor]

**Comment by lochidev** [comment]
I'll look into as soon I am free ♥

**Comment by lochidev** [comment]
You use "$|$" instead of "[cursor]" in the latest release now :D

**Comment by Masacroso** [comment]
> You use "$|$" instead of "[cursor]" in the latest release now :D

Unfortunately this fails in internet browsers, but it works in some other apps. In internet browsers it seems to work in some delayed way. I opened a ticket [here](https://github.com/lochidev/TextToolsPro/issues/17).
