### ISSUE TITLE
versioning issue

### ISSUE THREAD

**Issue by IzzySoft** [lochidev/TextComparePro#6]
It seems your `versionCode` is never increased. This means updates never reach those having the app already installed, as Android considers them the same as the installed version. Please take care to always increase `versionCode` when making a release.

**Comment by lochidev** [comment]
Thank you for pointing that out! I did increase the versioncode but VS decided to set it to 1 during compilation :(

**Comment by IzzySoft** [comment]
I've no idea with VS, I only see the result unfortunately. So :crossed_fingers: you find the culprit and can get around it with the next release! Thanks for checking, and best luck!

**Comment by lochidev** [comment]
I think the issue should be fixed now :D

**Comment by IzzySoft** [comment]
Reached my repo, so you're probably right – thanks!

**Comment by IzzySoft** [comment]
Looks like we have a versioning issue again, @lochidev: the one you have "Re-release for IzzyOnDroid repo to pickup the newest version" in the changelog won't ever reach IzzyOnDroid:

```
package: name='com.dingleinc.texttoolspro' versionCode='200024' versionName='7.1.0'
package: name='com.dingleinc.texttoolspro' versionCode='25' versionName='7.1.1'
```

it has DECREASED `versionCode`, so it's considered older – but pulled each day over and again. It further seems to trigger a rare bug in fdroidserver, which when processing it crashes. I was wondering today why it crashed the third time in a row now on its update run, then discovered this when running the update with full output:

    FileNotFoundError: [Errno 2] No such file or directory: 'archive/icons/com.dingleinc.texttoolspro.25.png'

(the bug happens when fdroidserver tries to extract the app icon from the APK, no idea why – I see no difference there to the previous release)

So we've had to disable updates for now. Can you please create another release with the APK having the correct `versionCode`?

**Comment by lochidev** [comment]
Hi, sorry I've been having trouble with armeabi-v7a recently so I had to delete and re-release the APKs. I just released [v7.1.2](https://github.com/lochidev/Expandroid/releases/tag/v7.1.2) with versioncode 26, I hope that fixes it!

**Comment by IzzySoft** [comment]
The last release at IoD had `versionCode: 200024`, so you cannot go below this without forcing everyone to uninstall and reinstall. So no, 26 would be downloaded, looked at by the process, and straight go to the bin as a higher VC is already in the repo, sorry.

**Comment by lochidev** [comment]
Ok I edited [v7.1.2](https://github.com/lochidev/Expandroid/releases/tag/v7.1.2) to have a new binary with version code 200026. 

I have no idea what happened here, looks like VS .net maui 9 messed up versioning when building APKs. It worked fine for AAB files :(

Anyway I think I have things figured out so shouldn't be a problem in the future.

Does the repo still pickup updates to a release version if I edit the release before 6pm UTC?  (I edited the v7.1.2 release with the new apk)

![Image](https://github.com/user-attachments/assets/84a73337-018c-4178-9a3b-6531ab92aef6)

**Comment by IzzySoft** [comment]
> Ok I edited [v7.1.2](https://github.com/lochidev/Expandroid/releases/tag/v7.1.2) to have a new binary with version code 200026.

Looks good, thanks!

> Does the repo still pickup updates to a release version if I edit the release before 6pm UTC?

Updates have been disabled for your app, see above 😜 I've just re-enabled them. And what do you mean by "edit the release"? Hopefully not "replacing the APK"? That would be bad practice (one should not **replace** what has already been distributed – which is why I asked for "another release" above. Because if it was fetched already, it won't be fetched again.

As the APK from the current release seems to be fine, updates have been re-enabled at IoD. Please take care future APKs will stay OK 😉

**Comment by lochidev** [comment]
Alrighty!  Pheww! 😅

**Comment by IzzySoft** [comment]
I'm especially happy it seems to not have triggered that fdroidserver bug again 🙈 Not good if each "automated" run needs "manual" action 🤪
